apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image
spec:
  selector:
    matchLabels:
      run: my-image
  replicas: 2
  template:
    metadata:
      labels:
        run: my-image
    spec:
      containers:
      - name: my-nginx
        image: ashaik65/myweb:1
        ports:
        - containerPort: 80
 ----
 
apiVersion: v1
kind: Service
metadata:
  name: my-image
  labels:
    run: my-image
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30020
  selector:
    run: my-image

    
    
