apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image
spec:
  selector:
    matchLabels:
      run: my-image
  replicas: 2
  template:
    metadata:
      labels:
        run: my-image
    spec:
      containers:
      - name: my-nginx
        image: ashaik65/myweb:1
        imagePullSecrets:
          - name: myregistrykey
        ports:
        - containerPort: 80
 
 


    
    
